
        <div class="py-4">
                        <!-- In my main I have articles from this weeks selection or our best  sells, but this is not yet generated by PHP via my data base.-->
                        <!--<div class="container">-->
                        <h4 class="card-tittle text-center text-secondary">Notre selection du moment/Offres du mois/Décès</h4>
    
                    <div class="row row-cols-1 row-cols-md-3 mb-5 g-5 text-center">
                        <?php  
                        foreach($product_list as $product){
                        //Here I do a request to my data base without doing a prepare because it isn't gonna change it is solid.(She display all the questions given) 
                        ?>    
                        <div class="col">
                            <div class="card shadow-sm">
                                <a href="/shop/<?=$product->getId()?>" >
                                <!--<img src="data:image/jpeg;base64,<?php //base64_encode($product->getImageList()[0]->getBin())?>" alt="<?=$product->getDescription()?>" width="100%" height="400">-->
                            </a>
                                    <div class="card-body text-center">
                                        <a class="produit-name" href="/shop/<?=$product->getId()?>" ><?=$product->getName()?></a>
                                        <p class="gy-2"><?= str_replace(".", ",", $product->getPrice()) ?> &euro;</p>
                              
                                    </div>   
                            </div>
                        </div>
            
                        <?php
                        }?>
                    </div>
        
        <!--</div>-->
        <a href="../views/shop.php"><h5 class="card-tittle text-bottom-left text-secondary">Voir plus de selections du moment</h5></a>
        </div>
        