
        <div class="py-4">
                        <!-- In my main I have articles from this weeks selection or our best  sells, but this is not yet generated by PHP via my data base.-->
                        <!--<div class="container">-->
                        <h4 class="card-tittle text-center text-secondary">Notre selection du moment/Offres du mois/Décès</h4>
    
                    <div class="row row-cols-1 row-cols-md-3 mb-5 g-5 text-center">
                        <?php  
                        foreach($produit_list as $produit){
                        //Here I do a request to my data base without doing a prepare because it isn't gonna change it is solid.(She display all the questions given) 
                        ?>    
                        <div class="col <?=$produit->getProduit_id()?>">
                            <div class="card shadow-sm">
                                <a href="article.php?produit_id=<?=$produit->getProduit_id()?>" >
                                <img src="data:image/jpeg;base64,<?=base64_encode($produit->getImage()->getImage_bin())?>" alt="<?=$produit->getProduit_description()?>" width="100%" height="400">
                            </a>
                                    <div class="card-body text-center">
                                        <a class="produit-name" href="article.php?produit_id=<?=$produit->getProduit_id()?>" >
                                        <?=$produit->getProduit_nom()?></a>
                                        <p class="gy-2"><?=$produit->getProduit_prix()?>€</p>
                              
                                    </div>   
                            </div>
                        </div>
            
                        <?php
                        }?>
                    </div>
        
        <!--</div>-->
        <a href="../views/shop.php"><h5 class="card-tittle text-bottom-left text-secondary">Voir plus de selections du moment</h5></a>
        </div>
        <div class="py-4">
        <h4 class="card-tittle text-center text-secondary">Offres du mois</h4>
        <div class="py-4">
                        <!-- In my main I have articles from this weeks selection or our best  sells, but this is not yet generated by PHP via my data base.-->
                        <!--<div class="container">-->
    
                    <div class="row row-cols-1 row-cols-md-4 mb-3 g-3 text-center">
                        <?php  
                        foreach($produit_list as $produit){
                        //Here I do a request to my data base without doing a prepare because it isn't gonna change it is solid.(She display all the questions given) 
                        ?>    
                        <div class="col <?=$produit->getProduit_id()?>">
                            <div class="card shadow-sm">
                                <a href="article.php?produit_id=<?=$produit->getProduit_id()?>" >
                                <img src="data:image/jpeg;base64,<?=base64_encode($produit->getImage()->getImage_bin())?>" alt="<?=$produit->getProduit_description()?>" width="100%" height="400">
                            </a>
                                    <div class="card-body text-center">
                                        <a class="produit-name" href="article.php?produit_id=<?=$produit->getProduit_id()?>" >
                                        <?=$produit->getProduit_nom()?></a>
                                        <p class="gy-2"><?=$produit->getProduit_prix()?>€</p>
                              
                                    </div>   
                            </div>
                        </div>
            
                        <?php
                        }?>
                    </div>
        <a href="../views/shop.php"><h5 class="card-tittle text-bottom-left text-secondary">Voir plus d'offres du mois</h5></a>
                </div>
                <div class="py-4">
        <h4 class="card-tittle text-center text-secondary">Blog</h4>
        <h5 class="card-tittle text-center text-secondary">Bouquets de mariages</h5>
        <a href="../views/blog.php"><h5 class="card-tittle text-bottom-left text-secondary">Voir nos bouquets de mariage</h5></a>
        <h5 class="card-tittle text-center text-secondary">Suivez notre activité sur nos réseaux sociaux</h5>
        <ul class="social-media nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-decoration-none social-icon social-icon-footer d-flex align-items-center justify-content-center" href="https://www.instagram.com/fcommefleursantibes/">
                        <i class="fa-brands fa-instagram">
                        </i>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-decoration-none social-icon social-icon-footer d-flex align-items-center justify-content-center" href="https://www.facebook.com/F-comme-Fleurs-Antibes-107206567645326">
                        <i class="fa-brands fa-facebook">
                        </i>
                        </a>
                    </li>
                </ul>


       